-- Migration: create_leaderboard
-- Created at: 2026-07-06T12:39:04.799Z
-- Generated by meoo db migrate

CREATE TABLE IF NOT EXISTS leaderboard (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, player_name text NOT NULL, score integer NOT NULL, level integer NOT NULL, mode text NOT NULL DEFAULT '1p', created_at timestamptz DEFAULT now()); ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY; CREATE POLICY lb_read ON leaderboard FOR SELECT USING (true); CREATE POLICY lb_insert ON leaderboard FOR INSERT WITH CHECK (true); CREATE INDEX IF NOT EXISTS leaderboard_score_idx ON leaderboard (score DESC);
